# Generated by Django 4.2 on 2024-01-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("base_currency", models.CharField(default="USD", max_length=3)),
                ("target_currency", models.CharField(max_length=3)),
                ("exchange_rate", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
